config/routes.rb
Tracker::Application.routes.draw do
  get "welcome/index"

  resources :beekeepers do
    resources :hives do
      resources :diseases
    end
  end

  root 'welcome#index'

end

app/models/beekeeper.rb
class Beekeeper < ActiveRecord::Base
  has_many :hives
end

app/models/disease.rb
class Disease < ActiveRecord::Base
  belongs_to :hive
end

app/models/hive.rb
class Hive < ActiveRecord::Base
  belongs_to :beekeeper
  has_many :diseases
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beekeepers_controller.rb
class BeekeepersController < ApplicationController
  def show
    @beekeeper = Beekeeper.find(params[:id])
  end

  def new
  end

  def create
    @beekeeper = Beekeeper.new(beekeeper_params)

    @beekeeper.save
    redirect_to @beekeeper
  end
 
  private
    def beekeeper_params
      params.require(:beekeeper).permit(:fname, :lname, :region)
    end
end

app/controllers/diseases_controller.rb
class DiseasesController < ApplicationController
end

app/controllers/hives_controller.rb
class HivesController < ApplicationController
   def show
    @hive = Hive.find(params[:id])
  end

  def new
  end

  def create
    @beekeeper = Beekeeper.find(params[:beekeeper_id])
    @hive = @beekeeper.hives.create(hive_params)
    redirect_to beekeeper_path(@beekeeper)
  end

  private
    def hive_params
      params.require(:hive).permit(:name, :population)
    end 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beekeepers_helper.rb
module BeekeepersHelper
end

app/helpers/diseases_helper.rb
module DiseasesHelper
end

app/helpers/hives_helper.rb
module HivesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/beekeepers/new.html.erb
<h1>Register as a new Beekeeper</h1>

<%= form_for :beekeeper, url: beekeepers_path do |f| %>
  <p>
    <%= f.label :"First name" %><br>
    <%= f.text_field :fname %>
  </p>
 
  <p>
    <%= f.label :"Last name" %><br>
    <%= f.text_field :lname %>
  </p>

  <p>
    <%= f.label :Region %><br>
    <%= f.text_field :region %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/beekeepers/show.html.erb
<h2>
  <strong>First name:</strong>
  <%= @beekeeper.fname %>
</h2>

<h2>
  <strong>Last name:</strong>
  <%= @beekeeper.lname %>
</h2>

<h2>
  <strong>Region:</strong>
  <%= @beekeeper.region %>
</h2>

<h3>Hives</h3>
<% @beekeeper.hives.each do |hive| %>
  <p>
    <strong>Hive name:</strong>
    <%= hive.name =%>
  </p>

  <p>
    <strong>Population</strong>
    <%= hive.population =%>
  </p>
<% end %>

<h3>Add a hive:</h3>
<%= form_for([@beekeeper, @beekeeper.hives.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :population %><br>
    <%= f.text_field :population %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'View hive details', beekeeper_hive_path(@hive,@beekeeper) %>

app/views/hives/show.html.erb
<h2>Hives</h2>
<% @beekeeper.hives.each do |hive| %>
  <p>
    <strong>Hive name:</strong>
    <%= hive.name =%>
  </p>

  <p>
    <strong>Population</strong>
    <%= hive.population =%>
  </p>
<% end %>

<h2>Diseases</h2>
<% @beekeeper.hives.each do |hive| %>
  <p>
    <strong>Hive name:</strong>
    <%= hive.name =%>
  </p>

  <p>
    <strong>Population</strong>
    <%= hive.population =%>
  </p>
<% end %>

<h2>Log a disease:</h2>
<%= form_for([@hive, @hives.disease.build]) do |f| %>
  <p>
    <%= f.label :disease %><br>
    <%= f.text_field :disease %>
  </p>
  <p>
    <%= f.label :date_found %><br>
    <%= f.text_field :date_found %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back to profile', beekeepers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tracker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to the Hives tracker</h1>
<p>The hives database allows apiarists and hobbists to keep track of the countries bee health by logging the condition of their hives as it changes.</p>